name: Trigger Shell Script on Push

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This checks out the repository

      - name: Verify current directory
        run: |
          pwd  # Prints the current working directory
          ls -al  # Lists all files in the current directory

      - name: Set up Python environment
        run: |
          python3 -m venv env  # Create a virtual environment if it doesn't exist
          source env/bin/activate  # Activate the virtual environment
          echo "Virtual environment activated"

      - name: Get latest code
        run: |
          git pull  # Pull the latest changes from the repository

      - name: Install Python requirements
        run: |
          pip install -r requirements.txt  # Install required Python packages

      - name: Create screen and run uvicorn
        run: |
          screen -dmS uvicorn_session uvicorn main:app --host 0.0.0.0 --port 8000  # Run uvicorn in a detached screen session
